[package]
name = "xcodeclean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
dirs = "4.0.0"
savefile = "0.12.0"
savefile-derive = "0.12.0"

